name: Build and Release Electron App

on:
  push:
    tags:
      - "v*" # Triggers on tags like v1.0.4

jobs:
  release:
    runs-on: windows-latest # Use windows-latest for Windows builds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build distributables
        run: npm run make

      - name: Publish to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
